export const NO_WALLET_ERROR = 'No wallet found in session'
export const NO_PARAM_ID_ERROR = 'Invalid or missing param ID'
export const NO_USER_IDENTITY_ERROR = 'No user identity found'
export const INVALID_CREATOR_ID_ERROR = 'Invalid or missing creator ID'
export const GENERIC_ERROR_MSG = 'An error occurred'
