import { IdentityPresenter } from 'types'

const FAKE_IDENTITIES: IdentityPresenter[] = [
  {
    asset_delta: '10',
    assets_sum: '100',
    contract: '0x123',
    conviction_price: '1',
    conviction_price_delta: '0.1',
    conviction_sum: '10',
    corpora_id: null,
    created_at: '2023-07-01T00:00:00Z',
    creator: {
      description: 'Creator 1',
      display_name: 'John Doe',
      ens_name: 'johndoe.eth',
      id: '1',
      image: 'https://example.com/avatar1.png',
      privy_id: '1',
      total: 100,
      wallet: '0x123',
    },
    creator_address: '0x123',
    creator_id: '1',
    description: 'Identity 1 description',
    display_name: 'Identity 1',
    entity_type: null,
    external_reference: null,
    follow_claim_id: '1',
    follow_vault_id: '1',
    followed_count: 10,
    follower_count: 20,
    id: '1',
    identity_hash: 'hash1',
    identity_id: '1',
    image: 'https://example.com/image1.png',
    is_contract: false,
    is_user: true,
    num_positions: 1,
    predicate: false,
    semantic: null,
    status: 'active',
    tag_count: 5,
    tags: null,
    updated_at: '2023-07-01T00:00:00Z',
    url: 'https://example.com',
    user: {
      description: 'User 1',
      display_name: 'John Doe',
      ens_name: 'johndoe.eth',
      id: '1',
      image: 'https://example.com/avatar1.png',
      privy_id: '1',
      total: 100,
      wallet: '0x123',
    },
    user_asset_delta: '5',
    user_assets: '50',
    user_conviction: '5',
    vault_id: '1',
    vault_uuid: null,
  },
  {
    asset_delta: '20',
    assets_sum: '200',
    contract: '0x456',
    conviction_price: '2',
    conviction_price_delta: '0.2',
    conviction_sum: '20',
    corpora_id: null,
    created_at: '2023-07-02T00:00:00Z',
    creator: {
      description: 'Creator 2',
      display_name: 'Jane Doe',
      ens_name: 'janedoe.eth',
      id: '2',
      image: 'https://example.com/avatar2.png',
      privy_id: '2',
      total: 200,
      wallet: '0x456',
    },
    creator_address: '0x456',
    creator_id: '2',
    description: 'Identity 2 description',
    display_name: 'Identity 2',
    entity_type: null,
    external_reference: null,
    follow_claim_id: '2',
    follow_vault_id: '2',
    followed_count: 15,
    follower_count: 25,
    id: '2',
    identity_hash: 'hash2',
    identity_id: '2',
    image: 'https://example.com/image2.png',
    is_contract: false,
    is_user: false,
    num_positions: 2,
    predicate: false,
    semantic: null,
    status: 'active',
    tag_count: 10,
    tags: null,
    updated_at: '2023-07-02T00:00:00Z',
    url: 'https://example.com',
    user: null,
    user_asset_delta: '10',
    user_assets: '100',
    user_conviction: '10',
    vault_id: '2',
    vault_uuid: null,
  },
  {
    asset_delta: '30',
    assets_sum: '300',
    contract: '0x789',
    conviction_price: '3',
    conviction_price_delta: '0.3',
    conviction_sum: '30',
    corpora_id: null,
    created_at: '2023-07-03T00:00:00Z',
    creator: {
      description: 'Creator 3',
      display_name: 'Alice Doe',
      ens_name: 'alicedoe.eth',
      id: '3',
      image: 'https://example.com/avatar3.png',
      privy_id: '3',
      total: 300,
      wallet: '0x789',
    },
    creator_address: '0x789',
    creator_id: '3',
    description: 'Identity 3 description',
    display_name: 'Identity 3',
    entity_type: null,
    external_reference: null,
    follow_claim_id: '3',
    follow_vault_id: '3',
    followed_count: 20,
    follower_count: 30,
    id: '3',
    identity_hash: 'hash3',
    identity_id: '3',
    image: 'https://example.com/image3.png',
    is_contract: false,
    is_user: true,
    num_positions: 3,
    predicate: false,
    semantic: null,
    status: 'active',
    tag_count: 15,
    tags: null,
    updated_at: '2023-07-03T00:00:00Z',
    url: 'https://example.com',
    user: {
      description: 'User 3',
      display_name: 'Alice Doe',
      ens_name: 'alicedoe.eth',
      id: '3',
      image: 'https://example.com/avatar3.png',
      privy_id: '3',
      total: 300,
      wallet: '0x789',
    },
    user_asset_delta: '15',
    user_assets: '150',
    user_conviction: '15',
    vault_id: '3',
    vault_uuid: null,
  },
]

export { FAKE_IDENTITIES }
